<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<!DOCTYPE ENTERTAINMENT [
<!ELEMENT ENTERTAINMENT (MUSIC+, MOVIES)>
<!ELEMENT MUSIC (ARTIST, GENRE, RECORD_LABEL)>
<!ELEMENT ARTIST (#PCDATA)>
<!ELEMENT GENRE (#PCDATA)>
<!ELEMENT RECORD_LABEL (#PCDATA)>
<!ELEMENT MOVIES (CATEGORY)>
<!ELEMENT CATEGORY (DRAMA+, ACTION+)>
<!ELEMENT DRAMA (TITLE, CAST, YEAR)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT CAST (#PCDATA)>
<!ELEMENT YEAR (#PCDATA)>
<!ELEMENT ACTION (LOCATION, DIRECTOR, SALES)>
<!ELEMENT LOCATION (#PCDATA)>
<!ELEMENT DIRECTOR (#PCDATA)>
<!ELEMENT SALES (#PCDATA)>
<!ATTLIST MUSIC id CDATA "1">
<!ATTLIST DRAMA id CDATA "1">
<!ATTLIST ACTION id CDATA "1">
]>
<ENTERTAINMENT>
	<MUSIC id="1">
		<ARTIST>Stonebowy</ARTIST>
		<GENRE>Dance Hall</GENRE>
		<RECORD_LABEL>Zylophone Music</RECORD_LABEL>
	</MUSIC>
	<MUSIC id="2">
		<ARTIST>Sarkodie</ARTIST>
		<GENRE>Rapper</GENRE>
		<RECORD_LABEL>Sarkcess Music</RECORD_LABEL>
	</MUSIC>

	<MOVIES>
		<CATEGORY>
			<DRAMA id="1">
				<TITLE>The Drunkard</TITLE>
				<CAST>Aja Koo</CAST>
				<YEAR>2018</YEAR>
			</DRAMA>
			<DRAMA id="2">
				<TITLE>The Pregnant Virgin</TITLE>
				<CAST>Ama Ghana</CAST>
				<YEAR>2015</YEAR>
			</DRAMA>
			<ACTION id="1">
				<LOCATION>United State</LOCATION>
				<DIRECTOR>Grant Doe</DIRECTOR>
				<SALES>$5000</SALES>
			</ACTION>
			<ACTION id="2">
				<LOCATION>China</LOCATION>
				<DIRECTOR>Chinsing Shua</DIRECTOR>
				<SALES>$12000</SALES>
			</ACTION>
		</CATEGORY>
	</MOVIES>
</ENTERTAINMENT> 